version: '3.8'
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: forum_db
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_USERNAME: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
    depends_on:
      - forum_db
    networks:
      - app
    user: "${UID}:${GID}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    networks:
      - app
    user: "${UID}:${GID}"

  forum_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "9906:${MYSQL_PORT}"
    networks:
      - app

volumes:
  mysql-data:

networks:
  app:
    driver: bridge